services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: all_landing_page
    ports:
      - "8000:8000"
    volumes:
      - .:/app # mount whole app, not just src
      - /app/node_modules # prevent overwriting node_modules
    command: npm run dev
    networks:
      - app-networks

volumes:
  pgdata:

networks:
  app-networks:
    driver: bridge
