export interface CaseStudy {
  id:              string;
  slug:            string;
  type?:           string;
  status:          string;
  title?:    string;
  description?:    string;
  image_url?:      string;
  image_alt?:      string;
  client_name?:    string;
  client_logo?:    string;
  client_industry?:string;
  client_domain?:  string;
  client_employees?:number;
  client_desc?:    string;
  challenge_intro?:string;
  solution_intro?: string;
  outcome_desc?:   string;
  outcome_video?:  string;
  meta_title?:     string;
  meta_desc?:      string;
  meta_keywords?:  string;
  calendly_url?:   string;
  tag_slugs:       string[];
  client_tags:     string[];
  hero_stats:      { value: string; label: string }[];
  metrics:         { value: string; label: string; sub?: string }[];
  challenge_items: { title: string; desc: string }[];
  solution_phases: { phase: string; time_range: string; desc: string }[];
  testimonials:    { quote: string; name: string; role: string; avatar_url?: string }[];
  created_at:      string;
  updated_at:      string;
}