import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/share/Navbar";
import Footer from "@/component/share/Footer";
import Provider from "./Provider";
import CustomCursor from "@/component/home/Softcursor";

const geistSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "400", "500", "600", "700", "900"],
});

const geistMono = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-black `}
      >
        <Provider>
          <CustomCursor />
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
