import { z } from "zod";

export const seoMetaSchema = z.object({
  id: z.string().uuid().optional(), // generated by DB
  page_name: z.enum([
    "home",
    "podcast",
    "shorts",
    "talking",
    "saas",
    "thumbnail",
    "portfolio",
    "career",
    "contact",
    "about",
    "blog",
    "terms",
    "privacy",
    "refund",
  ]),
  meta_title: z.string().min(1, "Meta title is required"),
  meta_description: z.string().min(1, "Meta description is required"),
  meta_keywords: z.string().optional(),

  canonical_url: z.string().url().optional(),
  meta_robots: z
    .enum([
      "index, follow",
      "noindex, nofollow",
      "index, nofollow",
      "noindex, follow",
    ])
    .default("index, follow"),
  schema: z.string().optional(),
  twitter_card_type: z.string().optional(),

  created_at: z.string().datetime().optional(),
  updated_at: z.string().datetime().optional(),
});

// ✅ For updating (PATCH / PUT)
export const updateSeoMetaSchema = seoMetaSchema.partial();

// ✅ For DB fetch or detailed view (includes required ID)
export const seoMetaWithIdSchema = seoMetaSchema.extend({
  id: z.string().uuid(),
});
