export type sectionName =
  | "short-hero"
  | "work"
  | "before_after"
  | "common_service"
  | "shorts_service"
  | "pricing"
  | "testimonial"
  | "process"
  | "industry"
  | "shorts_insight"
  | "whychooseus"
  | "faq"
  | "common_contact"
  | "podacast-hero"
  | "workwithcompany-2-line"
  | "podcast_contact"
  | "saas-hero "
  | "home-brand"
  | "saas_customer"
  | "whysaas_video"
  | "thumbnail_hero";
